### ISSUE TITLE
Compilation failure: cannot find symbol in CalciteQueryTest

### ISSUE THREAD

**Issue by asdf2014** [apache/druid#16049]
### Affected Version

29.0.0

### Description

![image](https://github.com/apache/druid/assets/8108788/b7210f03-3936-4b18-bfad-a8821c7a9b96)

**Comment by asdf2014** [comment]
This seems to be introduced by https://github.com/apache/druid/pull/15957

**Comment by asdf2014** [comment]
There is another "cannot find symbol" issue in DruidSqlParserImpl:

```java
/Users/asdf2014/code/druid/sql/target/generated-sources/org/apache/druid/sql/calcite/parser/DruidSqlParserImpl.java:1150:40
java: cannot find symbol
  symbol:   method convertSqlNodeToGranularityThrowingParseExceptions(org.apache.calcite.sql.SqlNode)
  location: class org.apache.druid.sql.calcite.parser.DruidSqlParserUtils
```

**Comment by kgyrtkirk** [comment]
conflicted changes were: #15996 and #15957
@gargvishesh  have opened #16050 to fix it
