### PR TITLE
upgrade shade

### PR DESCRIPTION
**Pull request by georgew5656**
Upgrade maven shade plugin to try to fix build failures

Sometimes we get maven shade errors in our integ tests becasue we don't run clean in between runs to clear the cache in order to speed them up. This can lead to the below error.
Error:  Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.2.4:shade (opentelemetry-extension) on project opentelemetry-emitter: Error creating shaded jar: duplicate entry: META-INF/services/org.apache.druid.opentelemetry.shaded.io.grpc.NameResolverProvider

See: https://issues.apache.org/jira/projects/MSHADE/issues/MSHADE-425?filter=allissues
An example run that failed: https://github.com/apache/druid/actions/runs/6301662092/job/17117142375?pr=14887

According to the ticket this is fixed by updating shade to 3.4.1.

When I updated to 3.4.1 I kept running into a different issue during static checks. (Caused by: java.lang.NoClassDefFoundError: com/github/rvesse/airline/parser/errors/ParseException)

I had to add the createDependencyReducedPom: false to get the build to pass.

The dependency reduced pom feature was added in 3.3.0 which we were not using before so setting it explicitly to false should not be a issue. https://issues.apache.org/jira/browse/MSHADE-36)
This PR has:

- [X] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by cryptoe** [comment]
@georgew5656 Could you add a bit more to description like which build failures were you seeing. 
What are the pro's and con's of `createDependencyReducedPom: false`. What is the impact. 

That would be helpful to make a decision on this PR.

**Comment by georgew5656** [comment]
> @georgew5656 Could you add a bit more to description like which build failures is this patch fixing. What are the pro's and con's of `createDependencyReducedPom: false`. What is the impact.
> 
> That would be helpful to make a decision on this PR.

sure, just updated

**Review by cryptoe — APPROVED** [review]
Changes lgtm!!

File: extensions-core/protobuf-extensions/pom.xml [hunk 1]
```diff
@@ -187,7 +187,7 @@
       <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-shade-plugin</artifactId>
-        <version>3.2.1</version>
+        <version>3.4.1</version>
```
Comment (xvrl) [inline extensions-core/protobuf-extensions/pom.xml:190]: I had to fix the same problem as part of https://github.com/apache/druid/pull/15014, any reason you did not upgrade to 3.5.0?

File: pom.xml [hunk 2]
```diff
@@ -1730,7 +1730,10 @@
                 <plugin>
                     <groupId>org.apache.maven.plugins</groupId>
                     <artifactId>maven-shade-plugin</artifactId>
-                    <version>3.2.4</version>
+                    <version>3.4.1</version>
+                    <configuration>
+                        <createDependencyReducedPom>false</createDependencyReducedPom>
+                    </configuration>
```
Comment (xvrl) [inline pom.xml:1736]: any reason we are setting this globally instead of defining it where we actually use the plugin?

File: extensions-core/protobuf-extensions/pom.xml (hunk 1 above)
Comment (xvrl) [reply extensions-core/protobuf-extensions/pom.xml:190]: also, why are we explicitly setting the plugin version here if it's already defined in the parent pom?

File: pom.xml (hunk 2 above)
Comment (georgew5656) [reply pom.xml:1736]: i wasn't able to figure out where the plugin was being used from the error messages I was seeing so i set it globally, the way you did it in the other pr was better

File: extensions-core/protobuf-extensions/pom.xml (hunk 1 above)
Comment (georgew5656) [reply extensions-core/protobuf-extensions/pom.xml:190]: no reason, i was trying to fix a issue in the unit tests where we were periodically getting: Error creating shaded jar: duplicate entry: META-INF/services/org.apache.druid.opentelemetry.shaded.io.grpc.NameResolverProvider if two builds ran two quickly one after another, and 3.4.1 was where the docs said this issue was fixed

File: pom.xml (hunk 2 above)
Comment (xvrl) [reply pom.xml:1736]: thanks, your PR actually helped me figure out why my build was failing initially. I had missed one of the uses of the plugin which was causing cryptic error messages.
